GET https://jsonplaceholder.typicode.com/comments?postId=1
# &abc=123
# &xyz=456

# Content-Type: application/json
# Authorization: Basic user:pass
# Authorization: Bearer abcd
# X-REQUEST-TYPE: GraphQL
# { "body": "1234" }



# ========================== #
# ======== RESPONSE ======== #
# ========================== #

HTTP/1.1 200 OK
Date: Tue, 14 Feb 2023 21:42:40 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: Express
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 999
X-Ratelimit-Reset: 1676394129
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Cache-Control: max-age=43200
Pragma: no-cache
Expires: -1
X-Content-Type-Options: nosniff
Etag: W/"5e6-4bSPS5tq8F8ZDeFJULWh6upjp7U"
Content-Encoding: gzip
Via: 1.1 vegur
CF-Cache-Status: HIT
Age: 16838
Server-Timing: cf-q-config;dur=7.9999990703072e-06
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Za9aJ3shL7zL4fuikNTXS3MJ8J4J%2BsRNaZDglD6i%2B86beLq1Jm5y9EwEeI%2B4UModc01vAc7XJRG7kEJ0CoS6g3XCZg5rtBOYob7055HGEqeSezpIS00Inq9b7L2P%2B3cE%2F4RAO5lWpBfemk2%2Boy0T"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 7998f9991f58a4bd-GRU
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

[
  {
    "postId": 1,
    "id": 1,
    "name": "id labore ex et quam laborum",
    "email": "Eliseo@gardner.biz",
    "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
  },
  {
    "postId": 1,
    "id": 2,
    "name": "quo vero reiciendis velit similique earum",
    "email": "Jayne_Kuhic@sydney.com",
    "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
  },
  {
    "postId": 1,
    "id": 3,
    "name": "odio adipisci rerum aut animi",
    "email": "Nikita@garfield.biz",
    "body": "quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione"
  },
  {
    "postId": 1,
    "id": 4,
    "name": "alias odio sit",
    "email": "Lew@alysha.tv",
    "body": "non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati"
  },
  {
    "postId": 1,
    "id": 5,
    "name": "vero eaque aliquid doloribus et culpa",
    "email": "Hayden@althea.biz",
    "body": "harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et"
  }
]
