// prettier-ignore
export const status = {
  100: { code: 100,   message: 'Informational',   description: "Continue" },
  101: { code: 101,   message: 'Informational',   description: "Switching protocols" },
  102: { code: 102,   message: 'Informational',   description: "Processing" },
  103: { code: 103,   message: 'Informational',   description: "Early Hints" },
  200: { code: 200,   message: 'Successful',      description: "OK" },
  201: { code: 201,   message: 'Successful',      description: "Created" },
  202: { code: 202,   message: 'Successful',      description: "Accepted" },
  203: { code: 203,   message: 'Successful',      description: "Non-Authoritative Information" },
  204: { code: 204,   message: 'Successful',      description: "No Content" },
  205: { code: 205,   message: 'Successful',      description: "Reset Content" },
  206: { code: 206,   message: 'Successful',      description: "Partial Content" },
  207: { code: 207,   message: 'Successful',      description: "Multi-Status" },
  208: { code: 208,   message: 'Successful',      description: "Already Reported" },
  226: { code: 226,   message: 'Successful',      description: "IM Used" },
  300: { code: 300,   message: 'Redirection',     description: "Multiple Choices" },
  301: { code: 301,   message: 'Redirection',     description: "Moved Permanently" },
  302: { code: 302,   message: 'Redirection',     description: "Found (Previously 'Moved Temporarily')" },
  303: { code: 303,   message: 'Redirection',     description: "See Other" },
  304: { code: 304,   message: 'Redirection',     description: "Not Modified" },
  305: { code: 305,   message: 'Redirection',     description: "Use Proxy" },
  306: { code: 306,   message: 'Redirection',     description: "Switch Proxy" },
  307: { code: 307,   message: 'Redirection',     description: "Temporary Redirect" },
  308: { code: 308,   message: 'Redirection',     description: "Permanent Redirect" },
  400: { code: 400,   message: 'Client Error',    description: "Bad Request" },
  401: { code: 401,   message: 'Client Error',    description: "Unauthorized" },
  402: { code: 402,   message: 'Client Error',    description: "Payment Required" },
  403: { code: 403,   message: 'Client Error',    description: "Forbidden" },
  404: { code: 404,   message: 'Client Error',    description: "Not Found" },
  405: { code: 405,   message: 'Client Error',    description: "Method Not Allowed" },
  406: { code: 406,   message: 'Client Error',    description: "Not Acceptable" },
  407: { code: 407,   message: 'Client Error',    description: "Proxy Authentication Required" },
  408: { code: 408,   message: 'Client Error',    description: "Request Timeout" },
  409: { code: 409,   message: 'Client Error',    description: "Conflict" },
  410: { code: 410,   message: 'Client Error',    description: "Gone" },
  411: { code: 411,   message: 'Client Error',    description: "Length Required" },
  412: { code: 412,   message: 'Client Error',    description: "Precondition Failed" },
  413: { code: 413,   message: 'Client Error',    description: "Payload Too Large" },
  414: { code: 414,   message: 'Client Error',    description: "URI Too Long" },
  415: { code: 415,   message: 'Client Error',    description: "Unsupported Media Type" },
  416: { code: 416,   message: 'Client Error',    description: "Range Not Satisfiable" },
  417: { code: 417,   message: 'Client Error',    description: "Expectation Failed" },
  418: { code: 418,   message: 'Client Error',    description: "I'm a Teapot" },
  421: { code: 421,   message: 'Client Error',    description: "Misdirected Request" },
  422: { code: 422,   message: 'Client Error',    description: "Unprocessable Entity" },
  423: { code: 423,   message: 'Client Error',    description: "Locked" },
  424: { code: 424,   message: 'Client Error',    description: "Failed Dependency" },
  425: { code: 425,   message: 'Client Error',    description: "Too Early" },
  426: { code: 426,   message: 'Client Error',    description: "Upgrade Required" },
  428: { code: 428,   message: 'Client Error',    description: "Precondition Required" },
  429: { code: 429,   message: 'Client Error',    description: "Too Many Requests" },
  431: { code: 431,   message: 'Client Error',    description: "Request Header Fields Too Large" },
  451: { code: 451,   message: 'Client Error',    description: "Unavailable For Legal Reasons" },
  500: { code: 500,   message: 'Server Error',    description: "Internal Server Error" },
  501: { code: 501,   message: 'Server Error',    description: "Not Implemented" },
  502: { code: 502,   message: 'Server Error',    description: "Bad Gateway" },
  503: { code: 503,   message: 'Server Error',    description: "Service Unavailable" },
  504: { code: 504,   message: 'Server Error',    description: "Gateway Timeout" },
  505: { code: 505,   message: 'Server Error',    description: "HTTP Version Not Supported" },
  506: { code: 506,   message: 'Server Error',    description: "Variant Also Negotiates" },
  507: { code: 507,   message: 'Server Error',    description: "Insufficient Storage" },
  508: { code: 508,   message: 'Server Error',    description: "Loop Detected" },
  510: { code: 510,   message: 'Server Error',    description: "Not Extended" },
  511: { code: 511,   message: 'Server Error',    description: "Network Authentication Required" }
}
