GET http://localhost:4000/returnRequest?
# &abc=123
# &xyz=456

# Content-Type: application/json
# Authorization: Basic user:pass
# Authorization: Bearer abcd
# X-REQUEST-TYPE: GraphQL
# { "body": "1234" }



# ========================== #
# ======== RESPONSE ======== #
# ========================== #
